### ISSUE TITLE
Command 'Split to New Component' resulted in an error

### ISSUE THREAD

**Issue by sarimarton** [welldone-software/react-component-splitter#9]
Hi,

When I select a JSX element and choose "Split to New Component" from the command palette, Visual Studio Code shows an error message: `Command 'Split to New Component' resulted in an error (command 'react-component-splitter.split' not found)`

My setup is

```
Visual Studio Code
Version: 1.65.2 (user setup)
Date: 2022-03-10T14:33:55.248Z (1 wk ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

**Comment by GautierAnd** [comment]
Same for me

**Comment by Sunsvision** [comment]
I think it's an installation issue, I've got the same and found how to fix it.
Go to your .vscode/extensions/saharavr.react-component-splitter-0.55.0 folder, open it in terminal and launch 
`npm i`
It should fix the problem.
Also I recommend open package.json in the same folder, find 
`editorHasSelection && resourceLangId == javascript`
and replace it with
`editorHasSelection && resourceLangId == javascriptreact`
so now it will work for jsx files from context menu, though it still will produce .js component file, it would be great if this extension can create folder structure as for components using jsx, scss...

**Comment by SaharAvr** [comment]
The issue was caused by a bug in eslint, which has since been fixed. In addition, the extension now also knows how to work with `.jsx` files (`resourceLangId` updated and, the file extension of the new component will now be the same as that of the original component). Please make sure to update the extension.

Thank you for bringing this to my attention and for your help in making this extension better.

@sarimarton @GautierAnd @Sunsvision
